# Generated by Django 6.0.4 on 2026-05-06 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChambreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_chambre', models.IntegerField(unique=True)),
                ('type_chambre', models.CharField(max_length=20)),
                ('etage', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('description', models.TextField()),
                ('dispo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('cin', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrive', models.DateField()),
                ('date_depart', models.DateField()),
                ('type_reservation', models.CharField(max_length=20)),
                ('nbr_personne', models.IntegerField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chambremodel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FactureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_nuitees', models.IntegerField(default=1)),
                ('services', models.FloatField(default=0.0)),
                ('remise', models.FloatField(default=0.0)),
                ('montant_total', models.FloatField(default=0.0)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.reservationmodel')),
            ],
        ),
    ]
