# Generated by Django 6.0.4 on 2026-05-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='montant_facture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='statut',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
