# Generated by Django 6.0.4 on 2026-05-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservationmodel_montant_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambremodel',
            name='equipements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chambremodel',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
