# Generated by Django 6.0.4 on 2026-05-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chambremodel_equipements_chambremodel_est_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TarifModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(max_length=20)),
                ('prix_par_nuit', models.FloatField()),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.saisonmodel')),
            ],
        ),
    ]
